### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by ryestew** [Machinalabs/remix-ethdoc-plugin#3]
Currently:
Activate
To be able to work with the plugin go to the plugins section and find EthDoc, then activate it.

Probably should be:
Activate
This plugin 2 parts the EthDoc Viewer & the EthDoc Generator.  They both need to be activated for the functionality to work.  The EthDoc Viewer appears in a tab in the Remix Editor.  EthDoc Generator's icon (needs a png of the icon) will appear in the icon panel when the plugin is activated. The plugin itself will appear in the side panel.

**Comment by ryestew** [comment]
I think the 1st paragraph needs a few edits:

EthDoc consists of 2 plugins:  the **EthDoc Viewer** and the **EthdDoc Generator**.  
The **EthDoc Generator** will activate the **EthDoc Viewer**, so to use EthDoc, you only need to **activate** EthDoc Generator.

The following image illustrates both sections of the plugin.

**Comment by ryestew** [comment]
And another update needed - to insure people know to click on the EthDoc tab. So here is this sentence:

Once the contracts are compiled, go to the EthDoc plugin section and you can select and preview the HTML documents that were generated.   

Maybe this should be:

Once the contracts are compiled, go to the EthDoc Generator in the side panel and click the button to generate the docs.  To see the generated docs, click the EthDoc Viewer tab in Remix's Editor.

**Comment by defiboy** [comment]
this has been updated !
